#!/bin/bash
#
#  When run from TextWrangler, this will execute a
#  "git commit" in the path of the frontmost document.
#
#  When called, it opens a temporary file in the system
#  editor for making commit comments.  The editor window
#  must be closed for the script to continue.
#
#  06-Sep-14
#  MJF

cd "${BB_DOC_PATH%/*}"		# Change to directory of frontmost file

Mtmp=$(mktemp /tmp/git-commit.XXXX)	#Create a temp file for comments

printf "Commit called from within TextWrangler.\n\n" >> $Mtmp

open -Wne $Mtmp || exit		# Open file to add comments ; the "W"
				# option waits until the editor is
				# closed before continuing script

git commit --file=$Mtmp &> /dev/null	# Commit

rm $Mtmp			# Remove temp file
